......tests.py:547: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.2.15', 55234), raddr=('162.242.248.45', 80)>
  data = data.json()
.tests.py:560: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.2.15', 55235), raddr=('162.242.248.45', 80)>
  data = data.json()
.....tests.py:569: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.2.15', 55236), raddr=('162.242.248.45', 80)>
  data = data.json()
.tests.py:589: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.2.15', 55237), raddr=('162.242.248.45', 80)>
  data = data.json()
.....tests.py:522: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.2.15', 55238), raddr=('162.242.248.45', 80)>
  data = data.json()
.tests.py:537: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.2.15', 55239), raddr=('162.242.248.45', 80)>
  data = data.json()
...FF...
======================================================================
FAIL: test_tweet_location_writability (__main__.testModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 420, in test_tweet_location_writability
    assert(new_tweet.city_id == new_location.id)
AssertionError

======================================================================
FAIL: test_tweets_attribute_readability (__main__.testModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 82, in test_tweets_attribute_readability
    assert (query.city_id == 5)
AssertionError

----------------------------------------------------------------------
Ran 27 tests in 4.190s

FAILED (failures=2)
